#!/usr/bin/env python3
"""
Supplementary Figure 2: BRCA1/BRCA2 sensitivity and specificity forest plots.

Reads Sup Table 7 and Sup Table 8 (generated by the BRCA integration pipeline) and outputs
PNG/PDF forest plots with colored labels based on CI thresholds.
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path

import matplotlib
import pandas as pd

# The publication pipeline is normally executed non-interactively (CI, Docker,
# or a remote compute node).  Force a raster backend before importing pyplot so
# figure generation never tries to open a platform GUI.
matplotlib.use("Agg")
import matplotlib.pyplot as plt


# Update these mappings if the input table headers change.
COLUMN_MAP = {
    "track": "Track",
    "ref_total": "Total",
    "sensitivity": "Sensitivity",
    "sens_ci_low": "95% CI lower",
    "sens_ci_high": "95% CI upper",
    "specificity": "Specificity",
    "spec_ci_low": "95% CI lower.1",
    "spec_ci_high": "95% CI upper.1",
}

SHEET_MAP = {
    "BRCA1": "Sup Table 7",
    "BRCA2": "Sup Table 8",
}


def _track_sort_key(track: str) -> tuple[int, str]:
    match = re.search(r"(\\d+)", str(track))
    number = int(match.group(1)) if match else 10**9
    return number, str(track)


def _load_table(path: Path, sheet: str, gene: str, column_map: dict[str, str]) -> pd.DataFrame:
    if path.suffix.lower() in {".xlsx", ".xls", ".xlsm"}:
        df = pd.read_excel(path, sheet_name=sheet, header=2)
    else:
        df = pd.read_csv(path)

    missing = [col for col in column_map.values() if col not in df.columns]
    if missing:
        raise KeyError(f"Missing columns in {sheet}: {missing}")

    data = pd.DataFrame(
        {
            "gene": gene,
            "track": df[column_map["track"]],
            "ref_total": df[column_map["ref_total"]],
            "sensitivity": df[column_map["sensitivity"]],
            "sens_ci_low": df[column_map["sens_ci_low"]],
            "sens_ci_high": df[column_map["sens_ci_high"]],
            "specificity": df[column_map["specificity"]],
            "spec_ci_low": df[column_map["spec_ci_low"]],
            "spec_ci_high": df[column_map["spec_ci_high"]],
        }
    )

    data["track"] = data["track"].astype(str).str.strip()
    data = data[data["track"].str.lower().ne("nan") & data["track"].ne("")]

    for col in [
        "ref_total",
        "sensitivity",
        "sens_ci_low",
        "sens_ci_high",
        "specificity",
        "spec_ci_low",
        "spec_ci_high",
    ]:
        data[col] = pd.to_numeric(data[col], errors="coerce")

    return data


def _ordered_tracks(data: pd.DataFrame) -> list[str]:
    tracks = data["track"].dropna().astype(str).str.strip().tolist()
    ordered: list[str] = []
    seen: set[str] = set()
    for track in tracks:
        match = re.search(r"(\\d+)", track)
        if match and int(match.group(1)) < 8:
            continue
        if track in seen:
            continue
        seen.add(track)
        ordered.append(track)
    return ordered


def _plot_panel(
    ax: plt.Axes,
    data_idx: pd.DataFrame,
    tracks: list[str],
    metric: str,
    ci_low: str,
    ci_high: str,
    title: str,
    panel_letter: str,
) -> None:
    x_positions = list(range(len(tracks)))
    ax.set_xticks(x_positions)
    ax.set_xticklabels(tracks, rotation=90, fontsize=5)
    ax.tick_params(axis="x", labelbottom=True)

    labels = ax.get_xticklabels()
    for i, track in enumerate(tracks):
        label_color = "black"
        if track not in data_idx.index:
            labels[i].set_color("red")
            continue

        row = data_idx.loc[track]
        if isinstance(row, pd.DataFrame):
            row = row.iloc[0]

        estimate = row[metric]
        low = row[ci_low]
        high = row[ci_high]
        ref_total = row.get("ref_total", float("nan"))
        missing = pd.isna(ref_total) or ref_total == 0 or pd.isna(estimate) or pd.isna(low) or pd.isna(high)

        if missing:
            label_color = "red"
        else:
            color = "blue" if low > 0.8 else "black"
            label_color = color
            lower_err = max(0.0, estimate - low)
            upper_err = max(0.0, high - estimate)
            ax.errorbar(
                i,
                estimate,
                yerr=[[lower_err], [upper_err]],
                fmt="o",
                color=color,
                ecolor=color,
                elinewidth=0.9,
                capsize=2,
                markersize=2,
            )

        labels[i].set_color(label_color)

    ax.set_xlim(-0.5, len(tracks) - 0.5)
    ax.set_ylim(0.0, 1.0)
    ax.set_yticks([0.0, 0.2, 0.4, 0.6, 0.8, 1.0])
    ax.set_yticklabels([f"{t:.1f}" for t in [0.0, 0.2, 0.4, 0.6, 0.8, 1.0]])
    ax.yaxis.grid(True, linestyle="--", color="lightgray", linewidth=0.6)
    ax.xaxis.grid(False)
    ax.set_axisbelow(True)
    ax.set_ylabel("")
    ax.set_title(title, fontsize=10, pad=6)
    ax.text(
        -0.06,
        1.05,
        panel_letter,
        transform=ax.transAxes,
        fontsize=12,
        fontweight="bold",
        ha="left",
        va="bottom",
        clip_on=False,
    )


def generate_supp_fig2(
    input_path: str | Path,
    output_prefix: str | Path = "figures/supp_fig2",
    brca1_sheet: str = SHEET_MAP["BRCA1"],
    brca2_sheet: str = SHEET_MAP["BRCA2"],
) -> tuple[Path, Path, Path]:
    input_path = Path(input_path)
    output_prefix = Path(output_prefix)
    output_prefix.parent.mkdir(parents=True, exist_ok=True)

    brca1 = _load_table(input_path, brca1_sheet, "BRCA1", COLUMN_MAP)
    brca2 = _load_table(input_path, brca2_sheet, "BRCA2", COLUMN_MAP)

    brca1_tracks = _ordered_tracks(brca1)
    brca2_tracks = _ordered_tracks(brca2)

    brca1_idx = brca1.drop_duplicates(subset=["track"]).set_index("track")
    brca2_idx = brca2.drop_duplicates(subset=["track"]).set_index("track")

    fig, axes = plt.subplots(4, 1, figsize=(16, 12))

    _plot_panel(
        axes[0],
        brca1_idx,
        brca1_tracks,
        "sensitivity",
        "sens_ci_low",
        "sens_ci_high",
        r"$\it{BRCA1}$ - Sensitivity with 95% Confidence Interval",
        "A",
    )
    _plot_panel(
        axes[1],
        brca1_idx,
        brca1_tracks,
        "specificity",
        "spec_ci_low",
        "spec_ci_high",
        r"$\it{BRCA1}$ - Specificity with 95% Confidence Interval",
        "B",
    )
    _plot_panel(
        axes[2],
        brca2_idx,
        brca2_tracks,
        "sensitivity",
        "sens_ci_low",
        "sens_ci_high",
        r"$\it{BRCA2}$ - Sensitivity with 95% Confidence Interval",
        "C",
    )
    _plot_panel(
        axes[3],
        brca2_idx,
        brca2_tracks,
        "specificity",
        "spec_ci_low",
        "spec_ci_high",
        r"$\it{BRCA2}$ - Specificity with 95% Confidence Interval",
        "D",
    )

    caption = (
        "Supplementary Figure 2. Forest plots depicting sensitivity and specificity for 185 "
        r"$\it{BRCA1}$"
        " (A,B)\n"
        "and 147 "
        r"$\it{BRCA2}$"
        " functional tracks (C,D). Lines denote 95% confidence intervals (CI). Tracks\n"
        "shown in blue font indicate those with the lower bound of the CI > 0.8. Tracks shown in red font\n"
        "did not test reference variants to allow calculation of specificity and sensitivity."
    )

    fig.subplots_adjust(left=0.06, right=0.995, top=0.95, bottom=0.2, hspace=0.8)
    fig.text(0.5, 0.04, caption, ha="center", va="bottom", fontsize=9)

    png_path = output_prefix.with_suffix(".png")
    pdf_path = output_prefix.with_suffix(".pdf")
    svg_path = output_prefix.with_suffix(".svg")
    fig.savefig(png_path, dpi=300)
    fig.savefig(pdf_path)
    fig.savefig(svg_path)
    plt.close(fig)

    return png_path, pdf_path, svg_path


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate Supplementary Figure 2 forest plots from Sup Table 7/8."
    )
    parser.add_argument(
        "--input",
        required=True,
        help="Path to Excel file generated by the BRCA integration pipeline.",
    )
    parser.add_argument(
        "--output-prefix",
        default="figures/supp_fig2",
        help="Output path prefix (without extension).",
    )
    parser.add_argument(
        "--brca1-sheet",
        default=SHEET_MAP["BRCA1"],
        help="Sheet name for BRCA1 tracks.",
    )
    parser.add_argument(
        "--brca2-sheet",
        default=SHEET_MAP["BRCA2"],
        help="Sheet name for BRCA2 tracks.",
    )
    args = parser.parse_args()

    png_path, pdf_path, svg_path = generate_supp_fig2(
        input_path=args.input,
        output_prefix=args.output_prefix,
        brca1_sheet=args.brca1_sheet,
        brca2_sheet=args.brca2_sheet,
    )
    print(f"Saved {png_path}, {pdf_path}, and {svg_path}")


if __name__ == "__main__":
    main()
